# Generated by Django 3.2.5 on 2021-08-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Bought', 'bought'), ('Not available', 'not available')], max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
