# Generated by Django 3.2.5 on 2021-08-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='qty_unit',
            field=models.CharField(choices=[('Kgs', 'Kilograms'), ('gms', 'grams'), ('pcs', 'pieces'), ('ltr', 'litres')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='quantity',
            field=models.FloatField(default=None),
        ),
    ]
