# Generated by Django 3.2.5 on 2021-08-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210811_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
