# Generated by Django 3.2.5 on 2021-08-15 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_grocerylist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='quantity',
            field=models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.0)),
        ),
    ]
