# Generated by Django 3.2.5 on 2021-08-15 05:21

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_grocerylist_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='quantity',
            field=models.FloatField(validators=[index.models.non_negative_qty]),
        ),
    ]
