# Generated by Django 3.2.5 on 2021-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_grocerylist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='user',
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='date_created',
            field=models.DateField(),
        ),
    ]
