# Generated by Django 3.2.5 on 2021-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210815_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='user',
            field=models.CharField(default='ramachandra', max_length=100),
            preserve_default=False,
        ),
    ]
