# Generated by Django 3.2.5 on 2021-08-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_grocerylist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
